/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Codigo.*;
import java.io.File;
import javax.swing.JOptionPane;

/**
 *
 * @author Ramso
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    
    private String ficheroActual=null;
    private Fichero f;
    private Punto[] puntos=null;
    private Algoritmo alg;
    private Triangulo tri;
    private int nt;
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //añadir titulos a los panel
        //panelGuardar.setVisible(false);
        
        alg = new Algoritmo();
        mostrarFicheros();
    }
    private void mostrarFicheros(){
        File carpeta = new File("./src/data");
        for(File fich: carpeta.listFiles()){
            if(fich.getName().contains(".tsp")){
                comboFicheros.addItem(fich.getName());
            }
        }
        //guardarSol.setVisible(false);
        //a=b=false;
    }
    public void mostrarPartA(int tipo){//1:exh | 2:DyV
        solucionFrame sf=new solucionFrame();
        
        long start = System.currentTimeMillis();
        if(tipo == 1) tri= alg.exhaustivo(puntos);
        else if(tipo == 2) tri= alg.DyV(puntos);
        
        long end = System.currentTimeMillis();
        canvasSolucion cs= new canvasSolucion(puntos,tri,ficheroActual);
        sf.setTitle("Solucion");
        sf.setSize(1025, 661);
        sf.add(cs);
        sf.setLocation(325, 5);
        sf.setResizable(true);
        
        sf.setVisible(true);
        campoTexto.setText(null);
        campoTexto.append("Fichero: "+ficheroActual);
        if(tipo == 1) campoTexto.append("\nSolucion Exhaustivo: ");
        else if(tipo == 2) campoTexto.append("\nSolucion DyV: ");
        campoTexto.append("\nTriangulo solucion");
        //campoTexto.append("\nPunto "+tri.getPuntoA().getID()+" ("+tri.getPuntoA().getX()+", "+tri.getPuntoA().getY()+")");
        campoTexto.append("\nPunto ("+tri.getA().getX()+", "+tri.getA().getY()+")");
        
        campoTexto.append("\nPunto ("+tri.getB().getX()+", "+tri.getB().getY()+")");
        campoTexto.append("\nPunto ("+tri.getC().getX()+", "+tri.getC().getY()+")");
        campoTexto.append("\nTiempo: "+(((double)end - (double)start)/1000)+"sg");
        campoTexto.setEditable(false);
        tipo=-1;
    
    }
    public void mostrarDijkstra(){
        long start1 = System.currentTimeMillis();
        alg.Dijkstra(puntos, Integer.valueOf(campoDijkstra.getText()));
        long end1 = System.currentTimeMillis();
        System.out.println("Dijkstra\nTiempo: "+(((double)end1 - (double)start1)/1000));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campoTexto = new javax.swing.JTextArea();
        panelAlgoritmos = new java.awt.Panel();
        botonExhaustivo = new javax.swing.JButton();
        botonDyV = new javax.swing.JButton();
        botonDijkstra = new javax.swing.JButton();
        campoDijkstra = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        panelGuardar = new java.awt.Panel();
        guardarSol = new javax.swing.JButton();
        campoNameFich = new javax.swing.JTextField();
        comboFicheros = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        campoPuntos = new javax.swing.JTextField();
        generaPuntos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        campoTexto.setColumns(20);
        campoTexto.setRows(5);
        jScrollPane1.setViewportView(campoTexto);

        botonExhaustivo.setText("Exhaustivo");
        botonExhaustivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExhaustivoActionPerformed(evt);
            }
        });

        botonDyV.setText("DyV");
        botonDyV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDyVActionPerformed(evt);
            }
        });

        botonDijkstra.setText("Dijkstra");
        botonDijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDijkstraActionPerformed(evt);
            }
        });

        label1.setText("label1");

        label2.setText("label2");

        label3.setText("Punto inicial:");

        javax.swing.GroupLayout panelAlgoritmosLayout = new javax.swing.GroupLayout(panelAlgoritmos);
        panelAlgoritmos.setLayout(panelAlgoritmosLayout);
        panelAlgoritmosLayout.setHorizontalGroup(
            panelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlgoritmosLayout.createSequentialGroup()
                        .addGroup(panelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonDyV, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonExhaustivo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAlgoritmosLayout.createSequentialGroup()
                        .addComponent(botonDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlgoritmosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        panelAlgoritmosLayout.setVerticalGroup(
            panelAlgoritmosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlgoritmosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonExhaustivo)
                .addGap(18, 18, 18)
                .addComponent(botonDyV)
                .addGap(20, 20, 20)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoDijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDijkstra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        guardarSol.setText("Guardar Solución");
        guardarSol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarSolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGuardarLayout = new javax.swing.GroupLayout(panelGuardar);
        panelGuardar.setLayout(panelGuardarLayout);
        panelGuardarLayout.setHorizontalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(guardarSol)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panelGuardarLayout.createSequentialGroup()
                .addComponent(campoNameFich)
                .addContainerGap())
        );
        panelGuardarLayout.setVerticalGroup(
            panelGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoNameFich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardarSol)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        comboFicheros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFicherosActionPerformed(evt);
            }
        });

        jLabel1.setText("Nuevos puntos:");

        generaPuntos.setText("Generar Puntos");
        generaPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaPuntosActionPerformed(evt);
            }
        });

        jButton1.setText("Comparar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(generaPuntos))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(panelAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton1)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboFicheros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(campoPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(generaPuntos)
                        .addGap(23, 23, 23)
                        .addComponent(panelGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAlgoritmos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboFicherosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFicherosActionPerformed
        // TODO add your handling code here:
        ficheroActual = comboFicheros.getSelectedItem().toString();
        f=new Fichero(ficheroActual);
        //Algoritmo alg = new Algoritmo();
        this.puntos = f.getPuntos();
    }//GEN-LAST:event_comboFicherosActionPerformed

    private void botonExhaustivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExhaustivoActionPerformed
        // TODO add your handling code here:
        mostrarPartA(1);
    }//GEN-LAST:event_botonExhaustivoActionPerformed

    private void botonDyVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDyVActionPerformed
        // TODO add your handling code here:
        mostrarPartA(2);
    }//GEN-LAST:event_botonDyVActionPerformed

    private void generaPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaPuntosActionPerformed
        // TODO add your handling code here:
        boolean b=false;
        try {
            Integer.parseInt(campoPuntos.getText());
            b=true;
            //System.out.println(campoPuntos.getText());
            //int da= Integer.valueOf(campoPuntos.getText());
            
        } catch (NumberFormatException excepcion) {
            b=false;
        }
        if(!b){
            JOptionPane.showMessageDialog(null, "Debe introducir un numero!");
        }else{
            int da=Integer.parseInt(campoPuntos.getText());;
            this.puntos = new Punto[da];
            nt=da;
            for(int i=0; i<da; i++){
                double x = Math.random()*1000 + 1;
                for(int j=0; j<da; j++){
                    double y = Math.random()*1000 + 1;
                    this.puntos[i]=new Punto(i,x,y);
                }
            }
            //a=true;
        }
        campoPuntos.setText("");
    }//GEN-LAST:event_generaPuntosActionPerformed

    private void guardarSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarSolActionPerformed
        // TODO add your handling code here:
        boolean b=false;
        try {
            Integer.parseInt(campoPuntos.getText());
            b=true;
            //System.out.println(campoPuntos.getText());
            //int da= Integer.valueOf(campoPuntos.getText());
            
        } catch (NumberFormatException excepcion) {
            b=false;
        }
        if(!b){
            JOptionPane.showMessageDialog(null, "Añadir nombre. Disponible solo con la opción Dijkstra!");
        }else{
            guardarSolucion g = alg.guardarDijkstra();
            f.Guardar(campoNameFich.getText(), g);
            JOptionPane.showMessageDialog(null, "Solución guardado correctamente en la carpeta Data del proyecto!");
            campoNameFich.setText("");
        }
    }//GEN-LAST:event_guardarSolActionPerformed

    private void botonDijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDijkstraActionPerformed
        // TODO add your handling code here:
        boolean b=false;
        try {
            Integer.parseInt(campoDijkstra.getText());
            b=true;
            //System.out.println(campoPuntos.getText());
            //int da= Integer.valueOf(campoPuntos.getText());
            
        } catch (NumberFormatException excepcion) {
            b=false;
        }
        if(!b){
            JOptionPane.showMessageDialog(null, "Debe de introducir un punto de inicio!");
        }else
        
        mostrarDijkstra();
        campoDijkstra.setText("");
    }//GEN-LAST:event_botonDijkstraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /* ejecuciones de 200, 500, 1500 y 5000*/
        int a200=200, a500=500, a1500=1500, a5000=5000;
        Punto[] p200 = new Punto[a200];
        //nt=da;
        for(int i=0; i<a200; i++){
            double x = Math.random()*1000 + 1;
            for(int j=0; j<a200; j++){
                double y = Math.random()*1000 + 1;
                p200[i]=new Punto(i,x,y);
            }
        }
        Punto[] p500 = new Punto[a500];
        //nt=da;
        for(int i=0; i<a500; i++){
            double x = Math.random()*1000 + 1;
            for(int j=0; j<a500; j++){
                double y = Math.random()*1000 + 1;
                p500[i]=new Punto(i,x,y);
            }
        }
        Punto[] p1500 = new Punto[a1500];
        //nt=da;
        for(int i=0; i<a1500; i++){
            double x = Math.random()*1000 + 1;
            for(int j=0; j<a1500; j++){
                double y = Math.random()*1000 + 1;
                p1500[i]=new Punto(i,x,y);
            }
        }
        Punto[] p5000 = new Punto[a5000];
        //nt=da;
        for(int i=0; i<a5000; i++){
            double x = Math.random()*1000 + 1;
            for(int j=0; j<a5000; j++){
                double y = Math.random()*1000 + 1;
                p5000[i]=new Punto(i,x,y);
            }
        }
        long start2, end2;
        //System.out.println("          \t200\t\t500\t\t1500\t\t5000");
        
        start2 = System.currentTimeMillis();
        alg.exhaustivo(p200);
        end2 = System.currentTimeMillis();
        System.out.print("Exhaustivo\t"+(((double)end2 - (double)start2)/1000)+"sg."); 
        start2 = System.currentTimeMillis();
        alg.exhaustivo(p500);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg."); 
        start2 = System.currentTimeMillis();
        alg.exhaustivo(p1500);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg."); 
        start2 = System.currentTimeMillis();
        alg.exhaustivo(p5000);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg."); 
        System.out.println("\n\nfin");
        //System.out.println("DyV");
        /*
        start2 = System.currentTimeMillis();
        alg.DyV(p200);
        end2 = System.currentTimeMillis();
        System.out.print("\nDyV       \t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DyV(p500);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DyV(p1500);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DyV(p5000);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        
        //System.out.println("Dijkstra");
           
        start2 = System.currentTimeMillis();
        alg.DijkstraTime(p200,0);
        end2 = System.currentTimeMillis();
        System.out.print("\nDijkstra  \t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DijkstraTime(p500,0);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DijkstraTime(p1500,0);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        start2 = System.currentTimeMillis();
        alg.DijkstraTime(p5000,0);
        end2 = System.currentTimeMillis();
        System.out.print("\t\t"+(((double)end2 - (double)start2)/1000)+"sg.");
        */
        System.out.println("");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDijkstra;
    private javax.swing.JButton botonDyV;
    private javax.swing.JButton botonExhaustivo;
    private javax.swing.JTextField campoDijkstra;
    private javax.swing.JTextField campoNameFich;
    private javax.swing.JTextField campoPuntos;
    private javax.swing.JTextArea campoTexto;
    private javax.swing.JComboBox<String> comboFicheros;
    private javax.swing.JButton generaPuntos;
    private javax.swing.JButton guardarSol;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Panel panelAlgoritmos;
    private java.awt.Panel panelGuardar;
    // End of variables declaration//GEN-END:variables
}
